version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBUG_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5080
    ports:
      - 8080:8080
      - 5080:5080
    hostname: localhost
    restart: unless-stopped
    networks:
      - mentor-portal-data
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:5.7
    restart: always
    networks:
      - mentor-portal-data
    environment:
      MYSQL_DATABASE: 'mentor_portal_db_dev'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: mysql-data

networks:
  mentor-portal-data:
