app:
  jwt:
    secret: "APP_SECRET"
    token-prefix: "Bearer "
    tokenExpirationAfterDays: 14

auth0:
  audience: ${AUDIENCE}
  issuer: ${ISSUER_URL}
  jwks: https://dev-0xs8ho26.us.auth0.com/.well-known/jwks.json

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ROOT}:${EXPOSED_DB_PORT}/${MYSQL_DATABASE_NAME}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_DATABASE_USER}
    password: ${MYSQL_DATABASE_PASSWORD}